from sqlalchemy.orm import Session
from app.models.user import User
from app.schemas.auth import SignupRequest


class UserRepository:
    def __init__(self, db: Session):
        """Inject the SQLAlchemy database session dependency."""
        self.db = db

    def get_by_email(self, email: str) -> User | None:
        """Find an existing user record by email."""
        return self.db.query(User).filter(User.email == email).first()

    def create_user(self, user_id: str, data: SignupRequest) -> User:
        """Saves a new user record to the relational PostgreSQL database.
        
        Note: We use the exact UUID generated by Supabase Auth as the local user ID.
        """
        db_user = User(
            id=user_id,
            email=data.email,
            name=data.name
        )
        self.db.add(db_user)
        self.db.commit()
        self.db.refresh(db_user)
        return db_user