from sqlalchemy.orm import Session
from fastapi import HTTPException, status
from app.core.supabase import supabase
from app.repositories.user_repository import UserRepository
from app.schemas.auth import SignupRequest


class AuthService:
    def __init__(self, db: Session):
        self.user_repo = UserRepository(db)

    def register_user(self, data: SignupRequest):
        """Orchestrates user creation across Supabase Auth and PostgreSQL database."""
        
        # 1. Enforce local constraints: Check if email is already taken in our DB
        existing_user = self.user_repo.get_by_email(data.email)
        if existing_user:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="A user with this email address already exists."
            )

        # 2. Register the user via the Supabase Auth Client
        try:
            auth_response = supabase.auth.sign_up({
                "email": data.email,
                "password": data.password,
                "options": {
                    "data": {
                        "name": data.name
                    }
                }
            })
        except Exception as e:
            # Catch Supabase API registration errors (e.g., password too weak, rate limits)
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Authentication service registration failed: {str(e)}"
            )

        # 3. Extract the unique user ID generated by Supabase
        if not auth_response.user or not auth_response.user.id:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="User was registered in Auth server, but no valid identifier was returned."
            )

        user_uuid = auth_response.user.id

        # 4. Synchronize the user details in our relational PostgreSQL database
        try:
            db_user = self.user_repo.create_user(user_id=user_uuid, data=data)
            return db_user
        except Exception as e:
            # Rollback plan: If the local database write fails, we have an orphaned record
            # inside Supabase Auth. We log this error to handle cleanup processes.
            # (In production, you would trigger an alert to support / sysadmins)
            print(f"CRITICAL ERROR: Failed to create public.users profile for UUID {user_uuid}: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Account created but profile synchronization failed. Please contact support."
            )